using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using Microsoft.Win32;

namespace ZoomBiDi;

internal sealed class TrayApp : ApplicationContext
{
    const string RunKeyPath = @"Software\Microsoft\Windows\CurrentVersion\Run";
    const string RunValueName = "ZoomBiDi";

    readonly Settings _settings;
    readonly Logger _log;
    readonly KeyboardMonitor _monitor;
    readonly NotifyIcon _tray;
    readonly Icon _iconOn, _iconOff;
    readonly ToolStripMenuItem _enabledItem, _rtlFirstItem, _alwaysItem, _startupItem, _debugItem;

    public TrayApp(Settings settings, Logger log, KeyboardMonitor monitor)
    {
        _settings = settings;
        _log = log;
        _monitor = monitor;
        _iconOn = LoadIcon("ZoomBiDi.ico");
        _iconOff = LoadIcon("ZoomBiDi-paused.ico");

        _enabledItem = new ToolStripMenuItem("Enabled", null, (_, _) => SetEnabled(!_monitor.Enabled));
        _rtlFirstItem = new ToolStripMenuItem("Only when the line starts in Hebrew", null, (_, _) => SetMode(InsertMode.RtlFirst));
        _alwaysItem = new ToolStripMenuItem("At the start of every line", null, (_, _) => SetMode(InsertMode.Always));
        _startupItem = new ToolStripMenuItem("Start with Windows", null, (_, _) => ToggleStartup());
        _debugItem = new ToolStripMenuItem("Debug log", null, (_, _) => ToggleDebug());

        var menu = new ContextMenuStrip();
        menu.Items.Add(_enabledItem);
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add(new ToolStripMenuItem("Insert direction mark") { Enabled = false });
        menu.Items.Add(_rtlFirstItem);
        menu.Items.Add(_alwaysItem);
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add(_startupItem);
        menu.Items.Add(_debugItem);
        menu.Items.Add("Open log", null, (_, _) => OpenFile(_log.FilePath));
        menu.Items.Add("Open settings file", null, (_, _) => OpenFile(_settings.FilePath));
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("Exit", null, (_, _) => ExitThread());
        menu.Opening += (_, _) => RefreshMenu();

        _tray = new NotifyIcon { ContextMenuStrip = menu, Visible = true };
        _tray.MouseClick += (_, e) => { if (e.Button == MouseButtons.Left) SetEnabled(!_monitor.Enabled); };
        RefreshMenu();
    }

    void SetEnabled(bool enabled)
    {
        _monitor.Enabled = enabled;
        _settings.Enabled = enabled;
        _settings.Save();
        RefreshMenu();
    }

    void SetMode(InsertMode mode)
    {
        _settings.Mode = mode;
        _settings.Save();
        RefreshMenu();
    }

    void ToggleDebug()
    {
        _settings.DebugLog = !_settings.DebugLog;
        _log.Enabled = _settings.DebugLog;
        _settings.Save();
        RefreshMenu();
    }

    static bool IsStartupEnabled()
    {
        using var key = Registry.CurrentUser.OpenSubKey(RunKeyPath);
        return key?.GetValue(RunValueName) is string;
    }

    void ToggleStartup()
    {
        using var key = Registry.CurrentUser.CreateSubKey(RunKeyPath);
        if (IsStartupEnabled()) key.DeleteValue(RunValueName, false);
        else key.SetValue(RunValueName, $"\"{Environment.ProcessPath}\"");
        RefreshMenu();
    }

    void RefreshMenu()
    {
        bool on = _monitor.Enabled;
        _enabledItem.Checked = on;
        _rtlFirstItem.Checked = _settings.Mode == InsertMode.RtlFirst;
        _alwaysItem.Checked = _settings.Mode == InsertMode.Always;
        _startupItem.Checked = IsStartupEnabled();
        _debugItem.Checked = _settings.DebugLog;
        _tray.Icon = on ? _iconOn : _iconOff;
        _tray.Text = on ? "ZoomBiDi – on (click to pause)" : "ZoomBiDi – paused (click to enable)";
    }

    static void OpenFile(string path)
    {
        try
        {
            if (!File.Exists(path)) File.WriteAllText(path, "");
            Process.Start(new ProcessStartInfo(path) { UseShellExecute = true });
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "ZoomBiDi");
        }
    }

    /// <summary>Loads an embedded .ico (generated by tools\MakeIcon.ps1) at the tray's small-icon size.</summary>
    static Icon LoadIcon(string resourceName)
    {
        using var stream = typeof(TrayApp).Assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException("Missing icon resource " + resourceName);
        return new Icon(stream, SystemInformation.SmallIconSize);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _tray.Visible = false;
            _tray.Dispose();
            _iconOn.Dispose();
            _iconOff.Dispose();
        }
        base.Dispose(disposing);
    }
}
